"""
Pydantic schemas for Gemini + MCP AI summary, grounded Q&A, and catalog chat.
"""
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class PlanetAISummaryResponse(BaseModel):
    """Factual natural-language summary synthesized by Gemini via MCP database tools."""
    planet_name: str = Field(..., description="Target planet designation")
    summary: str = Field(..., description="Factual narrative summary")
    key_facts: List[str] = Field(default_factory=list, description="Bulleted key facts")
    tools_used: List[str] = Field(default_factory=list, description="MCP tools invoked during generation")
    source: str = Field(default="Gemini + Exoplanet MCP Server (Grounded on Database Records)")


class PlanetQARequest(BaseModel):
    """User question about a specific planet."""
    question: str = Field(..., min_length=2, max_length=500, description="Natural language question about the planet")


class PlanetQAResponse(BaseModel):
    """Answer generated by Gemini via MCP database tools."""
    planet_name: str = Field(..., description="Target planet designation")
    question: str = Field(..., description="Original user question")
    answer: str = Field(..., description="Grounded factual answer or explicit unavailability statement")
    confidence: str = Field(default="High (Grounded on Database Records via MCP)")
    tools_used: List[str] = Field(default_factory=list, description="MCP tools invoked to answer the question")
    data_points_used: List[str] = Field(default_factory=list, description="Fields referenced from database")


class AIChatRequest(BaseModel):
    """General user inquiry about exoplanets, systems, or stars."""
    message: str = Field(..., min_length=2, max_length=1000, description="User prompt or question")
    context_planet: Optional[str] = Field(None, description="Optional active planet context")


class AIChatResponse(BaseModel):
    """Conversational answer generated by Gemini via MCP database tools."""
    message: str = Field(..., description="Original user message")
    response: str = Field(..., description="Grounded response from Gemini")
    tools_used: List[str] = Field(default_factory=list, description="MCP tools called during query execution")
    source: str = Field(default="Gemini + Exoplanet MCP Server")
